sonar.projectKey=surajtiwari688_ai-devops-chatbot
sonar.organization=surajtiwari688

sonar.sources=app
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/tests/**
sonar.qualitygate.wait=true